spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/demo1
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.oauth2.client.registration.google.client-id=695193443628-35fccic5p84a2rk5507rbu5tkula1690.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRlc3QxMjM0NTY3ODkw
spring.jpa.hibernate.ddl-auto=update
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=images